from time import sleep

print ("Error Code:1.334dr system malfunction")
sleep (1)
print ("ERROR")
sleep (1)
print ("ERROR")
sleep (1)
print ("ERROR")
sleep (1)
print ("ERROR")
sleep (1)
print ("ERROR")
sleep (1)
print ("ERROR")
sleep (1)
print ("ERROR")
sleep (1)
print ("ERROR")
sleep (1)
print ("ERROR")
sleep (2)
print ("hahaha, just kidding all is good as you were")
